# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weibo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weibo
#   pod 'HandyJSON', '~> 5.0.1'
#   pod 'SwiftyJSON'
#   pod 'Alamofire'
   pod "AFNetworking"
   pod "SDWebImage"
   pod "YYModel"
   pod "FMDB"
   pod "SVProgressHUD"
   pod "pop"


  target 'WeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeiboUITests' do
    # Pods for testing
  end

end
